[tool.poetry]
name = "fleecekmbackend"
version = "0.1.0"
description = ""
authors = ["nociza <azicon@berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
sqlalchemy = "^2.0.28"
databases = "^0.9.0"
aiosqlite = "^0.20.0"
pandas = "^2.2.1"
uvicorn = "^0.28.0"

[tool.poetry.scripts]
start = "uvicorn fleecekmbackend.main:app --host 0.0.0.0 --port 8000"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
